export const FETCH_POLLS = "FETCH_POLLS";
export const FETCH_POLLS_SUCCESS = "FETCH_POLLS_SUCCESS";
export const FETCH_POLLS_FAIL = "FETCH_POLLS_FAIL";

export const FETCH_POLL_DETAIL = "FETCH_POLL_DETAIL";
export const FETCH_POLL_DETAIL_SUCCESS = "FETCH_POLL_DETAIL_SUCCESS";
export const FETCH_POLL_DETAIL_FAIL = "FETCH_POLL_DETAIL_FAIL";

export default {
  FETCH_POLLS,
  FETCH_POLLS_SUCCESS,
  FETCH_POLLS_FAIL,
  FETCH_POLL_DETAIL,
  FETCH_POLL_DETAIL_SUCCESS,
  FETCH_POLL_DETAIL_FAIL,
};
