export const FETCH_POLLS = "FETCH_POLLS";
export const FETCH_POLLS_SUCCESS = "FETCH_POLLS_SUCCESS";
export const FETCH_POLLS_FAIL = "FETCH_POLLS_FAIL";

export const FETCH_POLL_DETAIL = "FETCH_POLL_DETAIL";
export const FETCH_POLL_DETAIL_SUCCESS = "FETCH_POLL_DETAIL_SUCCESS";
export const FETCH_POLL_DETAIL_FAIL = "FETCH_POLL_DETAIL_FAIL";

export const UPDATE_VOTES = "UPDATE_VOTES";
export const UPDATE_VOTES_SUCCESS = "UPDATE_VOTES_SUCCESS";
export const UPDATE_VOTES_FAIL = "UPDATE_VOTES_FAIL";

export default {
  FETCH_POLLS,
  FETCH_POLLS_SUCCESS,
  FETCH_POLLS_FAIL,
  FETCH_POLL_DETAIL,
  FETCH_POLL_DETAIL_SUCCESS,
  FETCH_POLL_DETAIL_FAIL,
  UPDATE_VOTES,
  UPDATE_VOTES_SUCCESS,
  UPDATE_VOTES_FAIL,
};
